### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by dragonlord2025** [restorer/gloomy-dungeons-2#1]
Using android studio 1.5

Error:Execution failed for task ':compileForgplayWithgplayWithzeemoteWithkoDebugNdk'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\AndroidNDK\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 1

**Comment by restorer** [comment]
Try to build from command line instead of Android Studio.
Forgot to mean that "Withko" mean to build korean version, probably you need "compileForgplayWithgplayWithzeemoteWoutkoDebug"

**Comment by restorer** [comment]
Just tried to build from Android Studio.
I need to change a few files for that, and everything compiles successfully.
Maybe you forget to add `ndk.dir` into `local.properties`?

**Comment by dragonlord2025** [comment]
I have downloaded ndk and added path to local.properties as well, after that when I try to run the game the above mentioned error is displayed.

I tried to run command **gradlew assembleDebug**  gives same error.

I did't understand how to run with z-build as you mentioned in the instructions.

Can you please tell how build from command line which command? I need to use z-buld? or how?

**Comment by restorer** [comment]
From README - `gradlew assembleForfdroidWoutgplayWoutzeemoteWoutkoDebug`
or if you want version for Google Play - `gradlew assembleForgplayWithgplayWithzeemoteWoutko`

**Comment by dragonlord2025** [comment]
Thanks for helping, I tried running **gradlew assembleForgplayWithgplayWithzeemoteWoutko** from command line
It gives following error.
Do I need to specify anything in **ndk-build.cmd file**? that's where its failing

Execution failed for task ':compileForgplayWithgplayWithzeemoteWoutkoDebugNdk'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\AndroidNDK\android-ndk-r10e\ndk-build.cmd'' finished with non-zero
> exit value 1

**Comment by restorer** [comment]
I don't use Windows for development, so can't help you with `ndk-build.cmd`.

Strange thing: you say you running `gradlew assembleForgplayWithgplayWithzeemoteWoutko` from command line, but exception is com.android.**ide**.common.process.ProcessException

**Comment by dragonlord2025** [comment]
I ran it from android studio terminal

On Sun, Dec 6, 2015 at 2:04 PM, Viachaslau Tratsiak <
notifications@github.com> wrote:

> Closed #1 https://github.com/restorer/gloomy-dungeons-2/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/restorer/gloomy-dungeons-2/issues/1#event-483650195.

## 

Shivaraj Patil | Triveous | shivrajp130@gmail.com urbaddy@gmail.com |
 +91-7353489699
