### ISSUE TITLE
Impossibly to use certain control's simultaneously

### ISSUE THREAD

**Issue by treakiandroid** [restorer/gloomy-dungeons-2#10]
Hi,

As i had to shoot my first enemy i realized that the control's as they are are totally useless. Its nice that you have added a free/analog view/aim function but what ever i tried in the settings there was no way to make the aiming and shopping simultaneously. So you have to aim, move your finger to thar trigger, shoot, then move your finger back to aiming. The impossibility to aim and shoot with toi fingers simultaneously (best one hand/finger aim, one hand shot) makes this new controls totally useless and ill better keep playing the old gloomy dungen even tho that i only have digital buttons (i am using classic layout where strave is under the fire button, so i can aim with my left hand and shoot with my right hand simultaneously)

I would be very glad if you could fix this big issue in the controls to make it usable at all or maybe for the meantime add a setting to get the old controls from gloomy dungeon back, so ill come back and give it another try.

Thanks for that in advance!

For now ill uninstall it do to this controls as they are are a pain in the ass...

**Comment by restorer** [comment]
I do not really understand what you mean. Why you want to shoot with one finger and aim with another?

Isn't it easier to shoot + aim with one finger? To do this just press "shoot" button, than doesn't release finger and aim, That's all.

There is no need to release a finger.
